#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.targetPresets=ios
# Раскомментируй, если сборка iOS падает из‑за кэша:
# kotlin.native.cacheKind=none

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

# Network timeout
org.gradle.workers.max=4

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
